author = "Ayush Biswas"

editor = "zed"

[code]
filename = '''
{{#with (regex_captures
  pattern="(?:problemset/problem|contest)/(\\d+)(?:/problem)?/([A-Za-z0-9]+)"
  on=url) as |url_parts|}}
  {{#with (regex_captures
    pattern="^[A-Za-z0-9]+\\.\\s*(.+)$"
    on=../title) as |title_parts|}}
./src/bin/{{url_parts._1}}-{{to_lower_case url_parts._2}}-{{to_kebab_case title_parts._1}}.rs
  {{/with}}
{{/with}}
'''
template = "./src/main.rs"
modifier = '''
{{!-- Triple braces to prevent html escaping --}}
{{!-- Base code block --}}
{{{code}}}

{{!-- Iterate over each library in lib_files --}}
{{#each lib_files}}
mod {{{@key}}} {
    {{{this}}}
}
{{/each}}
'''

[include]
cpio = "./src/cpio.rs"
itertools = "./src/itertools.rs"
binary_lifting = "./src/binary_lifting.rs"
combinatorics = "./src/combinatorics.rs"
dsu = "./src/dsu.rs"
lazy_segment_tree = "./src/lazy_segment_tree.rs"
modint = "./src/modint.rs"
segment_tree = "./src/segment_tree.rs"
sieve = "./src/sieve.rs"

[toggle]
create_file = true
run_on_save = true
submit_on_ac = true
