author = "Ayush Biswas"

editor = "zed"

[code]
filename = '''
{{#if (regex_is_match pattern="codeforces.com" on=url)}}
  {{#with (regex_captures
    pattern="(?:problemset/problem|contest)/(\\d+)(?:/problem)?/([A-Za-z0-9]+)"
    on=url) as |url_parts|}}
    {{#with (regex_captures
      pattern="^[A-Za-z0-9]+\\.\\s*(.+)$"
      on=../title) as |title_parts|}}
./src/bin/{{url_parts._1}}-{{to_lower_case url_parts._2}}-{{to_kebab_case title_parts._1}}.rs
    {{/with}}
  {{/with}}
{{/if}}
{{#if (regex_is_match pattern="atcoder.jp" on=url)}}
{{#with (regex_captures
  pattern="contests/([^/]+)/tasks/([^_]+)_([a-z]+)"
  on=url) as |url_parts|}}
  {{#with (regex_captures
    pattern="^[A-Za-z0-9]+\\s*\\-\\s*(.+)$"
    on=../title) as |title_parts|}}
./src/bin/{{url_parts._1}}-{{to_lower_case url_parts._3}}{{#if (to_kebab_case title_parts._1)}}-{{to_kebab_case title_parts._1}}{{/if}}.rs
  {{/with}}
{{/with}}
{{/if}}
'''
template = "./src/main.rs"
modifier = '''
{{!-- Triple braces to prevent html escaping --}}
{{!-- Base code block --}}
{{{code}}}

{{!-- Iterate over each library in lib_files --}}
{{#each lib_files}}
mod {{{@key}}} {
    {{{this}}}
}
{{/each}}
'''

[include]
cpio = "./src/lib/cpio.rs"
itertools = "./src/lib/itertools.rs"
superslice = "./src/lib/superslice.rs"
dsu = "./src/lib/dsu.rs"
scc = "./src/lib/scc.rs"
twosat = "./src/lib/twosat.rs"
sieve = "./src/lib/sieve.rs"
convolution = "./src/lib/convolution.rs"
fenwicktree = "./src/lib/fenwicktree.rs"
internal_bit = "./src/lib/internal_bit.rs"
internal_math = "./src/lib/internal_math.rs"
internal_queue = "./src/lib/internal_queue.rs"
internal_scc = "./src/lib/internal_scc.rs"
internal_type_traits = "./src/lib/internal_type_traits.rs"
mincostflow = "./src/lib/mincostflow.rs"
maxflow = "./src/lib/maxflow.rs"
binary_lifting = "./src/lib/binary_lifting.rs"
math = "./src/lib/math.rs"
string = "./src/lib/string.rs"
lazysegtree = "./src/lib/lazysegtree.rs"
modint = "./src/lib/modint.rs"
segtree = "./src/lib/segtree.rs"

[toggle]
create_file = true
run_on_save = true
submit_on_ac = true
